spring.application.name=apiGateway
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8010/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=users-status-check

#route request to this uri........
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USERS

#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/status/check

#INCOMING URL PATH: CLIENT SEND REQUEST TO THIS ------------->
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/USERS/users/status/check

spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Method=GET
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RemoveRequestHeader=Cookie

#2 PARAMETERS: 1.External Path 2.Internal Path -------------->
#spring.cloud.gateway.server.webflux.routes[0].filters[1]=RewritePath=/USERS/users/status/check, /users/status/check
spring.cloud.gateway.server.webflux.routes[0].filters[1]=RewritePath=/USERS/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webflux.routes[0].predicates[2]=Header=Authorization,Bearer .*
spring.cloud.gateway.server.webflux.routes[0].filters[2]=AuthorizationHeader

#CREATING USER ACCOUNT ----> NOT REQUIRED AUTHORIZATION FILTER
spring.cloud.gateway.server.webflux.routes[1].id=USERS
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USERS
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/USERS/users
spring.cloud.gateway.server.webflux.routes[1].predicates[1]=Method=POST
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[1].filters[1]=RewritePath=/USERS/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webflux.routes[2].id=USERS-h2-console
spring.cloud.gateway.server.webflux.routes[2].uri=lb://USERS
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/USERS/h2-console
spring.cloud.gateway.server.webflux.routes[2].predicates[1]=Method=GET
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[2].filters[1]=RewritePath=/USERS/(?<segment>.*), /${segment}


spring.cloud.gateway.server.webflux.routes[4].id=USERS-get-update-delete
spring.cloud.gateway.server.webflux.routes[4].uri=lb://USERS
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/USERS/users/**
spring.cloud.gateway.server.webflux.routes[4].predicates[1]=Method=GET,PUT,DELETE
spring.cloud.gateway.server.webflux.routes[4].predicates[2]=Header=Authorization,Bearer (.*)
spring.cloud.gateway.server.webflux.routes[4].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[4].filters[1]=AuthorizationHeader
spring.cloud.gateway.server.webflux.routes[4].filters[2]=RewritePath=/USERS/(?<segment>.*), /${segment}


#CONFIGURE ROUTES FOR LOGIN IN API GATEWAY ----------->
spring.cloud.gateway.server.webflux.routes[3].id=USERS-login
spring.cloud.gateway.server.webflux.routes[3].uri=lb://USERS

#we don't have to explicitly configure this endpoint in users service, it is byDefault by spring
#spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/USERS/login

#custom login url - check users application.properties
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/USERS/users/login

#spring.cloud.gateway.server.webflux.routes[3].predicates[1]=Method=POST
spring.cloud.gateway.server.webflux.routes[3].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[3].filters[1]=RewritePath=/USERS/(?<segment>.*), /${segment}


management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted

#SAME AS USER MICROSERVICES
token.secret=VQ7yTeEx\=Ko4vf56i+FpkLpbvdsVgzlU1vwk9To1o+yTE/O+xCSI\=coz+GuPP3ah3f6Sg4ghXQOeV61Xppqy6sktwEpA7