spring.application.name=apiGateway
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8010/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=users-status-check
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USERS

#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/status/check

#INCOMING URL PATH: CLIENT SEND REQUEST TO THIS ------------->
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/USERS/users/status/check

#spring.cloud.gateway.server.webflux.routes[0].predicates[1]=METHOD=GET
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RemoveRequestHeader=Cookie

#2 PARAMETERS: 1.External Path 2.Internal Path -------------->
#spring.cloud.gateway.server.webflux.routes[0].filters[1]=RewritePath=/USERS/users/status/check, /users/status/check
spring.cloud.gateway.server.webflux.routes[0].filters[1]=RewritePath=/USERS/(?<segment>.*), /${segment}

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted