spring.application.name=account-mgmt
server.port=0

eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka

spring.rabbitmq.host=localhost
spring.rabbitmq.post=15672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest